=== sheepfling/sturdy-broccoli/artifacts/siso_downloads/_expanded/SISO-STD-014.1-2018GDLSchemaFiles/SISO-STD-014/UseCases.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?copyright statement="Copyright (c) 2018 by the Simulation Interoperability Standards Organization, Inc.
P.O. Box 781238
Orlando, FL 32878-1238, USA
All rights reserved.

SISO hereby grants a general, royalty-free license to copy, distribute, display, and 
make derivative works from this material, for all purposes, provided that any use of the material 
contains the following attribution: “Reprinted with permission from SISO Inc.” Should 
a reader require additional information, contact the SISO Inc. Board of Directors.

SISO Inc. Board of Directors
P.O. Box 781238
Orlando, FL 32878-1238, USA"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
		   xmlns:gdl="http://www.sisostds.org/schemas/gdl" targetNamespace="http://www.sisostds.org/schemas/gdl">
	<xs:import namespace="http://www.w3.org/XML/1998/namespace"/>
	<xs:complexType name="UseCases">
		<xs:sequence>
			<xs:element ref="gdl:UseCase" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="UseCases" type="gdl:UseCases"/>
	<xs:complexType name="UseCase">
		<xs:sequence>
			<xs:element ref="gdl:UseCaseID"/>
			<xs:element ref="gdl:UseCaseName"/>
			<xs:element ref="gdl:UseCaseDescription"/>
			<xs:element ref="gdl:ScenarioParameters"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="UseCase" type="gdl:UseCase"/>
	<xs:complexType name="ScenarioParameters">
		<xs:sequence>
			<xs:element ref="gdl:PersistentObjectCount"/>
			<xs:element ref="gdl:TransientObjectCount"/>
			<xs:element ref="gdl:UpdateRate"/>
			<xs:element ref="gdl:TrafficPattern"/>
			<xs:element ref="gdl:ComplexityOfTranslation"/>
			<xs:element ref="gdl:ObjectCreation"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="ScenarioParameters" type="gdl:ScenarioParameters"/>
	<xs:element name="ObjectCreation">
		<xsd:annotation>
			<xsd:documentation>Object creation types are based on their creation time relative to the duration of the simulation exercise.
			</xsd:documentation>
		</xsd:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Static">
					<xsd:annotation>
						<xsd:documentation>Creation of persistent object at the beginning of the simulation execution.
						</xsd:documentation>
					</xsd:annotation>
				</xs:enumeration>
				<xs:enumeration value="Dynamic">
					<xsd:annotation>
						<xsd:documentation>Creation of objects dynamically during the simulation execution.
						</xsd:documentation>
					</xsd:annotation>
				</xs:enumeration>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="PersistentObjectCount" type="gdl:LMH"/>
	<xs:element name="UseCaseID" type="xs:string"/>
	<xs:element name="TrafficPattern">
		<xsd:annotation>
			<xsd:documentation>Defines the pattern of communications through a gateway.
			</xsd:documentation>
		</xsd:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Continuous">
					<xsd:annotation>
						<xsd:documentation>Each second of average network traffic throughput is plus or minus 10% from the previous second.
						</xsd:documentation>
					</xsd:annotation>
				</xs:enumeration>
				<xs:enumeration value="Burst Mode">
					<xsd:annotation>
						<xsd:documentation>Network traffic includes bursts of 50% more packets than the average network traffic.
						</xsd:documentation>
					</xsd:annotation>
				</xs:enumeration>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="UpdateRate" type="gdl:LMH"/>
	<xs:element name="TransientObjectCount" type="gdl:LMH"/>
	<xs:element name="UseCaseDescription" type="xs:string"/>
	<xs:element name="ComplexityOfTranslation" type="gdl:LMH"/>
	<xs:element name="UseCaseName" type="xs:string"/>
	<xs:simpleType name="LMH">
		<xsd:annotation>
			<xsd:documentation>Sets a qualitative value for rates, counts, and algorithmic complexities that the assigner needs to compare to the current state-of-the-art, rather than fixed values.
			</xsd:documentation>
		</xsd:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Low">
				<xsd:annotation>
					<xsd:documentation>Distinctly less than the typical value for a simulation exercise.
					</xsd:documentation>
				</xsd:annotation>
			</xs:enumeration>
			<xs:enumeration value="Medium">
				<xsd:annotation>
					<xsd:documentation>Typical value for a simulation exercise.
					</xsd:documentation>
				</xsd:annotation>
			</xs:enumeration>
			<xs:enumeration value="High">
				<xsd:annotation>
					<xsd:documentation>Distinctly greater than the typical value for a simulation exercise.
					</xsd:documentation>
				</xsd:annotation>
			</xs:enumeration>
			<xs:enumeration value="VeryHigh">
				<xsd:annotation>
					<xsd:documentation>Substantially greater than the typical value for a simulation exercise.
					</xsd:documentation>
				</xsd:annotation>
			</xs:enumeration>
			<xs:enumeration value="ExtremelyHigh">
				<xsd:annotation>
					<xsd:documentation>Monumentally greater than the typical value for a simulation exercise.
					</xsd:documentation>
				</xsd:annotation>
			</xs:enumeration>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== sheepfling/sturdy-broccoli/artifacts/siso_downloads/_expanded/SISO-STD-014.1-2018GDLSchemaFiles/SISO-STD-014/GDL_UseCases_instance.xml
<UseCases xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance xsi:noNamespaceSchemaLocation="schemas/gdl/UseCases.xsd">
	<UseCase>
		<UseCaseID>Case 1</UseCaseID>
		<UseCaseName>Small Virtual Application</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of translating between two simulation environments with a low number of persistent and transient objects with a high update rate. The message traffic would be continuous. The complexity of the translations would be low, implying simple objects and minimal translations. No new persistent objects would be created or deleted during the execution. Profile 1 might be characterized by a hardware-in-the-loop or a human-in-the-loop virtual simulator with small numbers of member applications.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>Low</PersistentObjectCount>
			<TransientObjectCount>Low</TransientObjectCount>
			<UpdateRate>High</UpdateRate>
			<TrafficPattern>Continuous</TrafficPattern>
			<ComplexityOfTranslation>Low</ComplexityOfTranslation>
			<ObjectCreation>Static</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
	<UseCase>
		<UseCaseID>Case 2</UseCaseID>
		<UseCaseName>Small LVC Event</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of a simulation environment with a low number of persistent objects and a medium number of transient messages. The update rate would be very high with a continuous traffic pattern. The translations would be of medium complexity. No new objects would be created during the execution of the simulation and all objects would be deleted at the end of the execution cycle.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>Medium</PersistentObjectCount>
			<TransientObjectCount>Medium</TransientObjectCount>
			<UpdateRate>VeryHigh</UpdateRate>
			<TrafficPattern>Continuous</TrafficPattern>
			<ComplexityOfTranslation>Medium</ComplexityOfTranslation>
			<ObjectCreation>Static</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
	<UseCase>
		<UseCaseID>Case 3</UseCaseID>
		<UseCaseName>Medium LVC Event</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of a medium number of persistent objects but a high number of transient messages. The update rate would be medium not exceeding 1 hertz. The traffic patterns would be “bursty” (more than 50% above the average numbers). The simulation would have a great number of updates in a short time period, followed by a lull. The translation complexity would be medium (more than direct algorithmic translations). Objects will be created and destroyed dynamically during the execution.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>Medium</PersistentObjectCount>
			<TransientObjectCount>High</TransientObjectCount>
			<UpdateRate>Medium</UpdateRate>
			<TrafficPattern>Burst Mode</TrafficPattern>
			<ComplexityOfTranslation>Medium</ComplexityOfTranslation>
			<ObjectCreation>Dynamic</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
	<UseCase>
		<UseCaseID>Case 4</UseCaseID>
		<UseCaseName>Large Constructive Application</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of a high number of persistent objects (greater than 10,000) and a medium number of transient messages (100 per second). The update rate would be low (20 persistent objects updated per second). The traffic pattern would be bursty. The translation complexity would be high. Objects will be created and destroyed dynamically during the execution.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>High</PersistentObjectCount>
			<TransientObjectCount>Medium</TransientObjectCount>
			<UpdateRate>Low</UpdateRate>
			<TrafficPattern>Burst Mode</TrafficPattern>
			<ComplexityOfTranslation>High</ComplexityOfTranslation>
			<ObjectCreation>Dynamic</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
	<UseCase>
		<UseCaseID>Case 5</UseCaseID>
		<UseCaseName>Large LVC Event</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of a high number of persistent and transient objects with a medium update rates. Bursty traffic would be used. The required translation complexity would be high. No new objects will be created during the execution and all objects would be destroyed at the end of the execution.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>High</PersistentObjectCount>
			<TransientObjectCount>High</TransientObjectCount>
			<UpdateRate>Medium</UpdateRate>
			<TrafficPattern>Burst Mode</TrafficPattern>
			<ComplexityOfTranslation>High</ComplexityOfTranslation>
			<ObjectCreation>Static</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
	<UseCase>
		<UseCaseID>Case 6</UseCaseID>
		<UseCaseName>High Count Event</UseCaseName>
		<UseCaseDescription><![CDATA[Consists of a very high number of persistent and transient objects, medium update rate with bursty traffic patterns.  Translation complexity would be medium with dynamic object creation and deletion.  This is an “extreme case” beyond the normal large LVC event to address a hypothetical future application that gateways might be expected to support.]]></UseCaseDescription>
		<ScenarioParameters>
			<PersistentObjectCount>VeryHigh</PersistentObjectCount>
			<TransientObjectCount>VeryHigh</TransientObjectCount>
			<UpdateRate>Medium</UpdateRate>
			<TrafficPattern>Burst Mode</TrafficPattern>
			<ComplexityOfTranslation>Medium</ComplexityOfTranslation>
			<ObjectCreation>Dynamic</ObjectCreation>
		</ScenarioParameters>
	</UseCase>
</UseCases>
