=== sheepfling/sturdy-broccoli/artifacts/siso_downloads/_expanded/SISO-STD-014-2/SISO-STD-014-2/GFL.xsd
<?xml version="1.0" encoding="UTF-8"?>
<?copyright statement="Copyright (c) 2018 by the Simulation Interoperability Standards Organization, Inc.
P.O. Box 781238
Orlando, FL 32878-1238, USA
All rights reserved.

SISO hereby grants a general, royalty-free license to copy, distribute, display, and 
make derivative works from this material, for all purposes, provided that any use of the material 
contains the following attribution: “Reprinted with permission from SISO Inc.” Should 
a reader require additional information, contact the SISO Inc. Board of Directors.

SISO Inc. Board of Directors
P.O. Box 781238
Orlando, FL 32878-1238, USA"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
		   xmlns="http://www.sisostds.org/schemas/gfl" xmlns:gfl="http://www.sisostds.org/schemas/gfl"
		   targetNamespace="http://www.sisostds.org/schemas/gfl">

	<!-- Root element -->
	<xs:element name="gfl">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="filter" type="gfl:filterType" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="boundingBox" type="geoBoundingBox"/>
	<xs:element name="boundingSphere" type="geoSphere"/>
	<xs:element name="boundingCylinder" type="geoCylinder"/>
	<!-- Basic bounding box defined by lower and upper corner. Conformant in content if not structure with OpenGIS Envelope. -->
	<xs:complexType name="geoBoundingBox">
		<xs:sequence>
			<xs:element name="lowerCorner" type="gfl:geoCoordinate" minOccurs="1" maxOccurs="1"/>
			<xs:element name="upperCorner" type="gfl:geoCoordinate" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="geoSphere">
		<xs:sequence>
			<xs:element type="geoCoordinate" name="center"/>
			<xs:element type="xs:double" name="radius"/>
		</xs:sequence>
		<xs:attribute name="lengthUnits" type="xs:string" use="required"/>
	</xs:complexType> 

	<xs:complexType name="geoCylinder">
		<xs:sequence>
			<xs:element type="geoCoordinate" name="center"/>
			<xs:element type="xs:double" name="radius"/>
			<xs:element name="height">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="direction" type="upOrDownType" default="up"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="lengthUnits" type="xs:string" use="required"/>
	</xs:complexType>

	<xs:simpleType name="upOrDownType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="up"/>
			<xs:enumeration value="down"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="geoCoordinate">
		<xs:sequence>
			<xs:element name="X" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Y" type="xs:double" minOccurs="1" maxOccurs="1"/>
			<xs:element name="Z" type="xs:double" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="crs" type="xs:string" use="optional"/>
	</xs:complexType>

	<!-- Filter for entity type. Includes optional filter on specific attribute values. -->
	<xs:complexType name="classFilterType">
		<xs:sequence>
			<xs:element name="classIdentifier" type="xs:string" minOccurs="1" maxOccurs="1"/>
			<!-- Assume attribute statements within a single entityFilterType are combined using "and" -->
			<xs:element name="attribute" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
						<!-- Pick either single value, list value (for arrays, lists, etc.), range of numeric values, or enumerated values -->
						<xs:choice minOccurs="1" maxOccurs="unbounded">
							<xs:element name="singleValue" type="xs:string"/>
							<xs:element name="listValue">
								<xs:simpleType>
									<xs:list itemType="xs:string"/>
								</xs:simpleType>
							</xs:element> 
							<!-- If low value omitted, assume negative infinity; for high value, positive infinity -->
							<xs:element name="rangeValue">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="lowValue" minOccurs="0" maxOccurs="1" type="xs:double"/>
										<xs:element name="highValue" minOccurs="0" maxOccurs="1" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="enumeratedValue">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="enumeration" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:sequence>
					<xs:attribute name="inOrOut" type="inOrOutType" default="in"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="inOrOut" type="inOrOutType" default="in"/>
	</xs:complexType>

	<xs:element name="geoFilter">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="boundingBox"/>
				<xs:element ref="boundingCylinder"/>
				<xs:element ref="boundingSphere"/>
			</xs:choice>
			<xs:attribute name="inOrOut" type="inOrOutType" default="in"/>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="inOrOutType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="in"/>
			<xs:enumeration value="out"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="classFilter" type="gfl:classFilterType"/>

	<xs:element name="relativeGeoFilter">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="instanceIdentifier" type="xs:string"/>
				<xs:element name="enclosingVolume" minOccurs="0" maxOccurs="1">
					<xs:complexType>
						<xs:choice>
							<xs:element name="cylinder">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="radius" type="xs:double"/>
										<xs:element name="height" type="xs:double" minOccurs="0" maxOccurs="1"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="sphere">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="radius" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="box">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="XLength" type="xs:double"/>
										<xs:element name="YLength" type="xs:double"/>
										<xs:element name="ZLength" type="xs:double"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:choice>
						<xs:attribute name="lengthUnits" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<!-- Filters have input and output sides (possibly multiple of either/both), a logic statement listing the filter conditions, the action to take on match, and an id.--> 
	<xs:complexType name="filterType">
		<xs:sequence>
			<xs:element name="appliesTo" minOccurs="1" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="fromSide" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
						<xs:element name="toSide" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:element name="all"/>
				<xs:element ref="filterStatement"/>
				<xs:element ref="gfl:logicStatement"/>
			</xs:choice>
			<xs:element name="action">
				<xs:complexType>
					<xs:choice minOccurs="1" maxOccurs="1">
						<xs:element name="stop">
							<xs:complexType></xs:complexType>
						</xs:element>
						<xs:element name="forward">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="rate" minOccurs="0" maxOccurs="1">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="value" type="xs:double" minOccurs="1" maxOccurs="1"/>
												<xs:element name="timeUnits" type="gfl:timeUnitEnum" default="seconds"/>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:choice>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
	</xs:complexType>

	<xs:simpleType name="timeUnitEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="milliseconds"/>
			<xs:enumeration value="seconds"/>
			<xs:enumeration value="minutes"/>
			<xs:enumeration value="hours"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="filterStatement">
		<xs:complexType>
			<xs:choice>
				<xs:element ref="gfl:geoFilter" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="gfl:relativeGeoFilter" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="gfl:classFilter" minOccurs="1" maxOccurs="1"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>

	<xs:element name="logicStatement" type="gfl:logicStatementType"/>

	<xs:complexType name="logicStatementType">
		<xs:sequence>
			<xs:choice>
				<xs:sequence>
					<xs:element name="openParen" minOccurs="1" maxOccurs="1">
						<xs:complexType></xs:complexType>
					</xs:element>
					<xs:choice>
						<xs:element ref="gfl:logicStatement"/>
						<xs:element ref="gfl:filterStatement"/>
					</xs:choice>
					<xs:choice minOccurs="0" maxOccurs="1">
						<xs:element ref="gfl:logicStatement"/>
						<xs:element ref="gfl:filterStatement"/>
					</xs:choice>
					<xs:element name="closeParen" minOccurs="1" maxOccurs="1">
						<xs:complexType></xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence>
					<xs:choice>
						<xs:element ref="gfl:logicStatement"/>
						<xs:element ref="gfl:filterStatement"/>
					</xs:choice>
					<xs:choice minOccurs="0" maxOccurs="1">
						<xs:element ref="gfl:logicStatement"/>
						<xs:element ref="gfl:filterStatement"/>
					</xs:choice>
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="operator" use="optional" type="gfl:logicOperators" default="and"/>
		<!-- Option to negate the statement (not the operator) -->
		<xs:attribute name="negate" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>

	<xs:simpleType name="logicOperators">
		<xs:restriction base="xs:string">
			<xs:enumeration value="and"/>
			<xs:enumeration value="or"/>
			<xs:enumeration value="xor"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== sheepfling/sturdy-broccoli/artifacts/siso_downloads/_expanded/SISO-STD-014-2/SISO-STD-014-2/GFL_example.xml
<?xml version="1.0" encoding="UTF-8"?> 
<gfl:gfl xmlns:srml="http://sisostds.org/schemas/srml" xmlns:gfl="http://www.sisostds.org/schemas/gfl" 
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="schemas/gfl/GFL.xsd"> 
 
 <!-- Basic GFL file demonstrating the use of the geoFilter, classFilter, and relativeGeoFilter filters --> 
 
 <!-- This example filters data from one simulation to another using a bounding sphere and limiting the rate at which matching data is forwarded. -->
 <gfl:filter id="geoExample"> 
  <!-- This filter applies to data from "SimulationX" and filters data going to "SimulationY" --> 
  <gfl:appliesTo> 
   <gfl:fromSide>SimulationX</gfl:fromSide> 
   <gfl:toSide>SimulationY</gfl:toSide> 
  </gfl:appliesTo> 
  <!-- The filter statement --> 
  <gfl:filterStatement> 
   <!-- A geofilter specified as a spherical volume-->
   <gfl:geoFilter> 
    <gfl:boundingSphere lengthUnits="meters"> <!-- radius units are meters --> 
     <!-- The center of the sphere in the simulation coordinate system -->
	 <gfl:center> 
      <gfl:X>23.45</gfl:X> 
      <gfl:Y>101.23</gfl:Y> 
      <gfl:Z>30.11</gfl:Z> 
     </gfl:center> 
     <!-- The radius of the sphere --> 
     <gfl:radius>500</gfl:radius> 
    </gfl:boundingSphere> 
   </gfl:geoFilter> 
  </gfl:filterStatement> 
  <!-- The action to take if the filter condition is met--> 
  <gfl:action> 
   <!-- Forward data... --> 
   <gfl:forward> 
    <!-- At a rate of 100 messages/second --> 
    <gfl:rate> 
     <gfl:value>100</gfl:value> 
     <gfl:timeUnits>seconds</gfl:timeUnits> 
    </gfl:rate> 
   </gfl:forward> 
  </gfl:action> 
 </gfl:filter> 
 
 <!-- This example filter demonstrates the use of class-attribute filtering stopping data from one simulation from going to two others if the specified attribute values are seen.--> 
 <gfl:filter id="classAttributeExample"> 
  <!-- This filter applies to data from "SimulationY" and filters data going to "SimulationZ" and "SimulationX" --> 
  <gfl:appliesTo> 
   <gfl:fromSide>SimulationY</gfl:fromSide> 
   <gfl:toSide>SimulationZ,SimulationX</gfl:toSide> 
  </gfl:appliesTo> 
  <!-- Use a class-attribute filter on class "Platform" and attribute "Type" --> 
  <gfl:filterStatement> 
   <gfl:classFilter> 
    <gfl:classIdentifier>Platform</gfl:classIdentifier> 
    <gfl:attribute> 
     <gfl:name>Type</gfl:name> 
     <!-- Filter on enumerated values "Car" and "Truck" for the "Type" attribute --> 
     <gfl:enumeratedValue> 
      <gfl:enumeration>Car</gfl:enumeration> 
      <gfl:enumeration>Truck</gfl:enumeration> 
     </gfl:enumeratedValue> 
    </gfl:attribute> 
   </gfl:classFilter> 
  </gfl:filterStatement> 
  <!-- Drop data meeting this filter rule --> 
  <gfl:action> 
   <gfl:stop/> 
  </gfl:action> 
 </gfl:filter> 
 
 <!-- This example filter demonstrates filtering on a relative spatial volume centered on a simulation entity, forwarding all data from one simulation to another if it is generated by entities or events within a cyclindrical volume around the sprecified entity. --> 
 <gfl:filter id="relativeGeoExample"> 
  <!-- This filter applies to data from "SimulationX" and filters data going to "SimulationZ" --> 
  <gfl:appliesTo> 
   <gfl:fromSide>SimulationX</gfl:fromSide> 
   <gfl:toSide>SimulationZ</gfl:toSide> 
  </gfl:appliesTo> 
  <gfl:filterStatement> 
   <!-- Filter on a simulation entity named "SimObjectInstance" --> 
   <gfl:relativeGeoFilter> 
    <gfl:instanceIdentifier>SimObjectInstance</gfl:instanceIdentifier> 
    <!-- Filter data around the entity in an enclosing cylinder --> 
    <gfl:enclosingVolume lengthUnits="meters"> 
     <gfl:cylinder> 
      <!-- Use a radius of 50 meters with the entity at the center --> 
      <gfl:radius>50</gfl:radius> 
      <!-- Use a height of 30 meters, split evenly on the entity (15 above, 15 below) --> 
      <gfl:height>30</gfl:height> 
     </gfl:cylinder> 
    </gfl:enclosingVolume> 
   </gfl:relativeGeoFilter> 
  </gfl:filterStatement> 
  <gfl:action> 
   <!-- Simply forward at the rate received--> 
   <gfl:forward/> 
  </gfl:action> 
 </gfl:filter> 
</gfl:gfl>
